// End-to-end regression test for the site search UI's Pagefind integration.
//
// This deliberately runs against a REAL Pagefind bundle generated by the
// installed Pagefind version (via its Node indexing API), served over a real
// HTTP server, executing real WASM. Nothing about the search API is stubbed.
//
// Why: the production bug was that Pagefind ships an ES module which *exports*
// its API, while the UI expected the older style where loading the script
// assigned `window.pagefind`. Every upstream signal looked healthy - the index
// built, pages were indexed, the file was served - and only an actual query
// failed. A test that asserts "the module loaded" would not have caught it.
// So this test asserts the thing that actually broke: that a query run through
// the search UI's own loader returns usable results.
//
// It is intentionally NOT pinned to how the API is reached (a global, a named
// export, a default export). If a future Pagefind changes that again, the UI
// must be updated, and this test fails until it is.

import assert from "node:assert/strict";
import fs from "node:fs/promises";
import http from "node:http";
import os from "node:os";
import path from "node:path";
import { after, before, describe, test } from "node:test";
import { pathToFileURL } from "node:url";

import { close, createIndex } from "pagefind";

import { createPagefindLoader, toSuggestions } from "../assets/search-client.js";

const INDEXED_TERM = "elixir";
const UNINDEXED_TERM = "zxqwvnothinghere";

const FIXTURE_PAGES = [
  {
    sourcePath: "catatan/belajar-elixir/index.html",
    content: `<!doctype html><html lang="id"><body><main>
      <h1>Belajar Elixir Dari Nol</h1>
      <p>Catatan tentang bahasa pemrograman Elixir dan ekosistem BEAM.</p>
    </main></body></html>`,
  },
  {
    sourcePath: "catatan/produktivitas/index.html",
    content: `<!doctype html><html lang="id"><body><main>
      <h1>Kebiasaan Produktif</h1>
      <p>Catatan tentang produktivitas sehari-hari saat menulis kode.</p>
    </main></body></html>`,
  },
];

describe("search UI against a real Pagefind bundle", () => {
  let server;
  let baseUrl;
  let bundleUrl;
  let tmpDir;

  before(async () => {
    tmpDir = await fs.mkdtemp(path.join(os.tmpdir(), "pagefind-search-test-"));

    const { index, errors } = await createIndex({ forceLanguage: "id" });
    assert.deepEqual(errors, [], "creating the Pagefind index should not error");

    for (const page of FIXTURE_PAGES) {
      const { errors: fileErrors } = await index.addHTMLFile(page);
      assert.deepEqual(fileErrors, [], `indexing ${page.sourcePath} should not error`);
    }

    const written = await index.writeFiles({ outputPath: path.join(tmpDir, "pagefind") });
    assert.deepEqual(written.errors, [], "writing the Pagefind bundle should not error");

    // Serve the generated bundle so Pagefind can fetch its own wasm and index
    // chunks over HTTP, exactly as a browser would.
    server = http.createServer(async (req, res) => {
      try {
        const { pathname } = new URL(req.url, "http://127.0.0.1");
        const body = await fs.readFile(path.join(tmpDir, decodeURIComponent(pathname)));
        res.writeHead(200);
        res.end(body);
      } catch {
        res.writeHead(404);
        res.end("not found");
      }
    });
    await new Promise((resolve) => server.listen(0, "127.0.0.1", resolve));

    baseUrl = `http://127.0.0.1:${server.address().port}/`;
    bundleUrl = pathToFileURL(path.join(tmpDir, "pagefind", "pagefind.js")).href;
  });

  after(async () => {
    await close();
    if (server) await new Promise((resolve) => server.close(resolve));
    if (tmpDir) await fs.rm(tmpDir, { recursive: true, force: true });
  });

  // The loader is given the real generated bundle. Only the URL is substituted,
  // because Node cannot resolve the browser's root-relative "/pagefind/...".
  function loadRealPagefind() {
    return createPagefindLoader({
      importPagefind: async () => {
        const mod = await import(bundleUrl);
        await mod.options({ basePath: `${baseUrl}pagefind/`, baseUrl: "/" });
        return mod;
      },
    });
  }

  test("a query for an indexed term returns renderable results", async () => {
    const ensurePagefind = loadRealPagefind();

    const pagefind = await ensurePagefind();
    const response = await pagefind.search(INDEXED_TERM, { limit: 6 });
    const suggestions = await toSuggestions(response, 6);

    assert.ok(suggestions.length > 0, `expected results for "${INDEXED_TERM}"`);

    const [first] = suggestions;
    assert.match(first.url, /belajar-elixir/);
    assert.equal(first.title, "Belajar Elixir Dari Nol");
    assert.match(first.excerpt, /<mark>/, "excerpt should carry Pagefind's highlight markup");
  });

  test("a query with no matches resolves to an empty list instead of throwing", async () => {
    const ensurePagefind = loadRealPagefind();

    const pagefind = await ensurePagefind();
    const response = await pagefind.search(UNINDEXED_TERM, { limit: 6 });
    const suggestions = await toSuggestions(response, 6);

    assert.deepEqual(suggestions, []);
  });
});

describe("search UI loading behaviour", () => {
  test("surfaces a rejection when Pagefind genuinely cannot be loaded", async () => {
    const ensurePagefind = createPagefindLoader({
      importPagefind: () => Promise.reject(new Error("network down")),
    });

    await assert.rejects(ensurePagefind(), /network down/);
  });

  test("rejects when the loaded module exposes no usable search API", async () => {
    const ensurePagefind = createPagefindLoader({
      importPagefind: async () => ({ somethingElse: true }),
    });

    await assert.rejects(ensurePagefind(), /Pagefind/);
  });

  test("loads once and shares the result across concurrent callers", async () => {
    let calls = 0;
    const ensurePagefind = createPagefindLoader({
      importPagefind: async () => {
        calls++;
        return { search: async () => ({ results: [] }) };
      },
    });

    const [a, b] = await Promise.all([ensurePagefind(), ensurePagefind()]);
    const c = await ensurePagefind();

    assert.equal(calls, 1, "Pagefind should only be imported once");
    assert.equal(a, b);
    assert.equal(b, c);
  });
});
